### ISSUE TITLE
Bot stall issue in `wrap.js`

### ISSUE THREAD

**Issue by arzulo** [matlab-discord/Matlab-Discord-Bot#17]
Seeing an error come back
```js
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/root/discord_bots/matlab_bot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/root/discord_bots/matlab_bot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async CommandInteraction.reply (/root/discord_bots/matlab_bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:99:5)
    at async Object.execute (/root/discord_bots/matlab_bot/commands/wrap.js:33:9)
    at async slashExecute (/root/discord_bots/matlab_bot/events/slashInteraction.js:8:13)
    at async Object.execute (/root/discord_bots/matlab_bot/events/interactionCreate.js:12:13)
    at async Client.<anonymous> (/root/discord_bots/matlab_bot/index.js:37:50) {
  method: 'post',
  path: '/interactions/966033515827302531/aW50ZXJhY3Rpb246OTY2MDMzNTE1ODI3MzAyNTMxOkNuakhCZzBqZjBRTXlxV1VMVWxKUFd6eHc0R1NFZFRFOUMwVnlWYzJib0dWWnRXT1JibU90ckt5eHRZUjI3TUxhNG01STQ4aGdmOWg2S2Jya3Zjb2FkWjM5Z1RhWXRsZUUwTDBKYTNWc2JNcUJjTU5WMkZpcmxrYXZVZlFQVm40/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}```

**Comment by arzulo** [comment]
Resolved since latest versions of discord.js
